### ISSUE TITLE
Tool descriptions my contain hrefs which are not rendered

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-xc-scripts#16]
Tool descriptions may contain html syntax (like hrefs) and need to be rendered in the tools pop-up.

**Comment by xogeny** [comment]
This can be done.  But let me know why (so far) it hasn't.  Rendering of HTML in this way a security issue.  It allows somebody somebody to put:

```
Tool such and such is so awesome, you really should use it!
<script>stealAllCredentialsInBrowserMemory();</script>
```

This is why this functionality is avoided and why the feature in React is named [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

All that being said, we dont (**currently**) have anything sensitive in memory in the browser since we aren't allowing the user to log in *and* we only allow vendors to specify the HTML.  

**Nevertheless**, I still think this is a bad precedent to set.  An alternative would be to allow text to be written in Markdown and the processed safely with [`react-markdown`](https://www.npmjs.com/package/react-markdown) (which makes a point of not allowing users to do inline HTML, if I understand correctly).

**Comment by andreas-junghanns** [comment]
Understood and accepted. Can we auto-convert from html to markup for those files that already exist?
Maybe we should even ban html and reject those files containing html?

**Comment by xogeny** [comment]
Moved to: https://github.com/modelica/fmi-crosscheck-tools/issues/6
