### ISSUE TITLE
open issues from last fmi steering committee meeting in Februay

### ISSUE THREAD

**Issue by APillekeit** [modelica/fmi-xc-scripts#18]
Hi,

please find below some points that have been discussed at the steering committee in February.

Please sort tool vendor names on the tools entry page alphbetically (currently capital and small letters are sorted seperatly)

The coloring on the entry page seems to be OK. 

But please remove coloring (red, green, gray) of tool vendors from the details page (please note: the coloring of the entry page is OK). Suggestion: color every tool vendor regardles to the cross check result in gray. It is unclear who is responsible for e.g. the failed imports and the the red coloring - is it the importing or the exporting tool? Thus coloring might be misleading. It is also not part of the cross check rules to do the coloring on the details page.

It would be also good to get at least an information, that the site is not working together with internet explorer if opened with internet explorer.

Thanks
Andreas

**Comment by xogeny** [comment]
I'm closing this issue because the issues raised here are related to the UI side of things, not the data collection scripts (which is what this repo contains).  For this reason, I have consolidated all the repositories into a single repository so there will be just a single issue tracker for all aspects of the tooling.

Please visit them and subscribe to them if you wish to be informed of updates:

[Sorting Issues](https://github.com/modelica/fmi-crosscheck-tools/issues/1)
[Coloring Issues](https://github.com/modelica/fmi-crosscheck-tools/issues/2)
[Internet Explorer](https://github.com/modelica/fmi-crosscheck-tools/issues/3)

**Comment by APillekeit** [comment]
Thank you for creating the new entries!

Andreas

AndreasPi ∙ • 484 ∙ PM-PVS ∙ X-D2.09
